libepoxy: Autospec creation for update from version 1.5.9 to version 1.5.10
Alex Richardson (1):
      Add the right include paths for EGL and X11 headers

Caolán McNamara (1):
      fix error: use of undeclared identifier 'OPENGL_LIB'

Emmanuele Bassi (1):
      Post-release version bump to 1.5.10

Seungha Yang (1):
      meson: Fix for building on non-English locale